services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=WdaDb;Username=postgres;Password=postgres"
      Authentication__SecretForKey: "IvDuXqMFRXyH+LaEoCD6lBTFqpSQrj0qKTjSV5Sm4XmMClTP/ucVEzfYtafP5vfQ1lDQYpKOocMe7VWGgRGn5Q=="
      Authentication__Issuer: "http://localhost:8080"
      Authentication__Audience: "wda.webapi"